GET http://localhost:5000/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNjM0Njg0NCwianRpIjoiMDcwOWIwZTUtZDYzMS00MTU3LThkZmQtNGQ5NTE3ZWU3MGFjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3RAZXhhbXBsZS5jb20iLCJuYmYiOjE3MzYzNDY4NDQsImNzcmYiOiJmOTgyMDhlMy02ZGVhLTRmZjktYmFkZS03MTY4YTU5MTNhMjIiLCJleHAiOjE3MzYzNTA0NDR9.lGxoVezEklVgO89KhEl48hbBZMmYQ22b01Y01slRkDY