GET http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNjMyNjg2NiwianRpIjoiM2ZlZDc0OTAtODQ4ZS00OTZkLTk5MDYtYmNjMDdmMjlkNzkxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3RAZXhhbXBsZS5jb20iLCJuYmYiOjE3MzYzMjY4NjYsImNzcmYiOiJmM2Q0YzQzYi02M2Y2LTQ4OGUtYWM5Yy00NjllYjE2OTgwMzMiLCJleHAiOjE3MzYzMzA0NjZ9.qU68JrQy35-E0SLjV2Jy8X3B0aC6lxMSUCy6_faLnFc
