GET http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNjI4OTk0NywianRpIjoiNThkNWNjMDMtZjNiZS00YzUyLWI1NDMtY2NiYTFmNDFlNjEzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc0BleGFtcGxlLmNvbSIsIm5iZiI6MTczNjI4OTk0NywiY3NyZiI6ImE0Nzk2ZWRkLWI5MjktNGJjMy1hNzBiLWM3MDQ5MTA2NmM3MCIsImV4cCI6MTczNjI5MzU0N30.2270FCAekYvjXB0HgE8Zn3X5JpAPFUyOlprIqDZjM1E
