GET http://localhost:5000/articles?page=3&limit=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNjM0NzE0NiwianRpIjoiZGMxZTA4ZjMtYzA1MC00ZmRiLTgxZjMtOTA3OTY1ZjA4ODQxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3RAZXhhbXBsZS5jb20iLCJuYmYiOjE3MzYzNDcxNDYsImNzcmYiOiIyNTUzNjRmYi0xZGFkLTRlYmMtOTBjNy03YTdjMWExNTdiMDkiLCJleHAiOjE3MzYzNTA3NDZ9.cSP3Og8oYSdH7HEw_KXqBjKDnFDFLyo-7RGybEzTWIM