GET http://localhost:5000/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNjMzODg2OCwianRpIjoiODA2NGY3NjYtNmJkOC00NzQzLTg3NjItNDYxMWFiMmNiNTQ1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyQGV4YW1wbGUuY29tIiwibmJmIjoxNzM2MzM4ODY4LCJjc3JmIjoiNzAyODE3NTQtOWIyZC00ODk1LWEyNWYtNWZlMjUwNzM5OTg5IiwiZXhwIjoxNzM2MzQyNDY4fQ.yYaAV5EUGE9qrtH2P1bmwtiNDBJhkS9GXYcMN5WYGZo