POST http://localhost:5000/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNjM0ODIzNSwianRpIjoiZTk1NzI3ZDItNWJhMy00ODFkLWEwODMtZTRmMWJmZmRmOTc3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3RAZXhhbXBsZS5jb20iLCJuYmYiOjE3MzYzNDgyMzUsImNzcmYiOiJiZDJjZmFkNS03ZjhhLTRmMTItYjc2ZS00ZjVhMzFmYzE4MTkiLCJleHAiOjE3MzYzNTE4MzV9.znqKfloCpK8G0hher4VaDXmUAds0zStBqwz-Gcl8_aE

    {
        "title": "Cooking with Fire Extinguishers: The Ultimate Kitchen Hack",
        "content": "Who needs an oven when you have a fire extinguisher? Learn how to extinguish hunger with this bold approach to modern cooking. Warning: Not for the faint of heart or taste buds.",
        "category": "Cooking"
    }