DELETE http://localhost:5000/articles/677e33d9cddb40a2a3e227e1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczNjMzMDgxMSwianRpIjoiYmViOTZkNjAtNmMyZS00NjVlLWE4NDUtZmFhZjQ1YTFkNGNjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InRlc3QyQGV4YW1wbGUuY29tIiwibmJmIjoxNzM2MzMwODExLCJjc3JmIjoiYTc5ZTJkMDUtYmI2MS00NDUxLTkyZmQtOGM5MjNkMWRlZTg5IiwiZXhwIjoxNzM2MzM0NDExfQ.LSUHi3E9DbF0IDBn4MvwXwKQHh0qZgZUbRdAophlZ2w